// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1) {
  return window['go']['manager']['Api']['Convert'](arg1);
}

export function GetConfig() {
  return window['go']['manager']['Api']['GetConfig']();
}

export function GetSetting() {
  return window['go']['manager']['Api']['GetSetting']();
}

export function SetConfig(arg1) {
  return window['go']['manager']['Api']['SetConfig'](arg1);
}
