// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manager} from '../models';
import {options} from '../models';

export function Convert(arg1:Array<string>):Promise<void>;

export function GetConfig():Promise<manager.Config>;

export function GetSetting():Promise<manager.Setting>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function SetConfig(arg1:manager.Config):Promise<manager.Config>;
